config/routes.rb
Inibon::Engine.routes.draw do

  root to: 'base#landing'

  resources :versions do
    collection do
      match :change, via: :all
    end
  end

  resources :locales do
    member do 
      match :from_yaml, via: :post
      match :missing, via: :all
    end
    resources :keys do
      collection do
        get 'find' => 'keys#find'
      end
      resources :translations
    end
    resources :translations do
      resources :keys do
        collection do
          get 'find' => 'keys#find'
        end
      end
    end
  end

  resources :keys do
    resources :translations
    resources :keys do
      collection do
        get 'find' => 'keys#find'
      end
    end

    resources :locales do
      resources :translations
    end
  end

  resources :translations do
    resources :keys do
      resources :locales, member: {from_yaml: :post}
    end
  end

end

app/models/inibon/hit.rb
class Inibon::Hit < ActiveRecord::Base

  self.table_name= 'inibon_hits'
  @@logger = ActiveSupport::Logger.new('log/inibon.log')

  belongs_to :translation

end

app/models/inibon/key.rb
class Inibon::Key < ActiveRecord::Base

  self.table_name= 'inibon_keys'
  @@logger = ActiveSupport::Logger.new('log/inibon.log')

  def self.model_name
    #@my_model_name ||= ::ActiveSupport::ModelName.new(name.demodulize)
    @my_model_name ||= ::ActiveModel::Name.new(self, Inibon)
  end

  has_ancestry

  has_many :translations, class_name: 'Inibon::Translation', foreign_key: :key_id
  has_many :locales, through: :translations, class_name: 'Inibon::Locale', foreign_key: :locale_id

  belongs_to :father, class_name: 'Inibon::Key', counter_cache: :children_count, optional: true
  has_many :sons, class_name: 'Inibon::Key', foreign_key: :father_id

  # This validation is important, otherwise /inibon/locales/ca/keys becomes @cain=[Inibon::Locale.param_find('ca'),Inibon::Key.param_find(nil)] 
  validates_presence_of :key 

  scope :with_missing_locales, ->(*x) {
    select('inibon_keys.*').joins(<<-joins).where('inibon_translations.id IS NULL AND inibon_keys.children_count IS NULL')
      left outer join inibon_locales on #{x.any? ? "inibon_locales.key IN ('#{x.join('\',\'')}')" : '1'}
      left outer join inibon_translations on inibon_translations.key_id = inibon_keys.id AND inibon_translations.locale_id = inibon_locales.id
      joins
  }

  scope :with_missing_version, ->(a,b) {
    select('inibon_keys.*').joins(<<-joins).where('inibon_versionings_b.translation_id IS NULL')
      INNER JOIN inibon_translations
        ON inibon_translations.key_id = inibon_keys.id
      INNER JOIN inibon_versionings
        ON inibon_versionings.translation_id = inibon_translations.id AND inibon_versionings.version_id = #{a}
      LEFT OUTER JOIN inibon_versionings as inibon_versionings_b
        ON inibon_versionings_b.translation_id = inibon_translations.id
        AND inibon_versionings_b.locale_id = inibon_versionings.locale_id
        AND inibon_versionings_b.version_id = #{b}
      joins
  }

  scope :in_locale, ->(l) {
    case l
    when  String, Symbol
      joins(:locales).where(inibon_locales: {key: l.to_s})
    else
      joins(:locales).where(inibon_locales: {id: l.id})
    end
  }

  scope :with_key, ->(k) { where(key: k.to_s.gsub(':','.')) }

  def diff_to(b)
    # Inibon::Key.
  end

  def self.with_differences(a,b)
    connection.execute(<<-SQL).to_a.to_h
      SELECT inibon_keys.key, inibon_translations.locale_id,  COUNT(DISTINCT inibon_translations.value) as cnt FROM inibon_keys
      LEFT OUTER JOIN inibon_translations
        ON inibon_translations.key_id = inibon_keys.id
      LEFT OUTER JOIN inibon_versionings
        ON inibon_versionings.translation_id = inibon_translations.id AND inibon_versionings.version_id IN (#{a},#{b},NULL)
      GROUP BY inibon_keys.key, inibon_translations.locale_id
      HAVING COUNT(DISTINCT inibon_translations.value) > 1
    SQL
  end

  def self.ensure_key(b)
    if x = Inibon::Key.find_by_key(b.to_s)
      yield(x) if block_given?
    else
      parts = b.to_s.split('.')
      x = parts.inject(nil) do |parent,el|
        Inibon::Key.find_by_key([*parent.try(:key),el]*'.') || Inibon::Key.create(key: [*parent.try(:key),el]*'.', parent: parent, father: parent)
      end
      yield(x) if block_given?
    end
    x
  end

  def missing_locales
    Inibon::Locale.
      where(['NOT EXISTS (select id from inibon_translations where inibon_translations.locale_id = inibon_locales.id AND inibon_translations.key_id = ?)',self.id])
  end

  def identification
    "#{self.class.model_name}: #{self.key}"
  end

  def to_param
    self.key.gsub('.',':')
  end

  def self.param_find(x)
    self.find_by_key(x.to_s.gsub(':','.'))
  end

end

app/models/inibon/locale.rb
class Inibon::Locale < ActiveRecord::Base

  self.table_name= 'inibon_locales'
  @@logger = ActiveSupport::Logger.new('log/inibon.log')

  def self.model_name
    #@my_model_name ||= ::ActiveSupport::ModelName.new(name.demodulize)
    @my_model_name ||= ::ActiveModel::Name.new(self, Inibon)
  end

  has_many :translations, class_name: 'Inibon::Translation', foreign_key: :locale_id
  has_many :keys, through: :translations, class_name: 'Inibon::Key', foreign_key: :key_id

  scope :in_locale, ->(l) {
    case l
    when  String, Symbol
        where(key: l.to_s)
    else
        where(id: l.id)
    end
  }

  scope :with_key, ->(k) {
    case k
    when  String, Symbol
      joins(:keys).where(inibon_keys: {key: k.to_s.gsub(':','.')})
    else
      joins(:keys).where(inibon_keys: {id: k.id})
    end
  }

  statux %w{wip available disabled}, required: true, column: :state, initial: 'wip'

  validates_uniqueness_of :key

  def self.with_locale(l)
    yield(find_by_key(l.to_s) || Inibon::Locale.create(key: l.to_s))
  end

  def chain
    [@self]
  end

  def identification
    "#{self.class.model_name}: #{self.name}"
  end

  def to_param
    self.key
  end

  def self.param_find(x)
    self.find_by_key(x.to_s)
  end

end

app/models/inibon/version.rb
# encoding: utf-8
class Inibon::Version < ActiveRecord::Base

  self.table_name= 'inibon_versions'
  @@logger = ActiveSupport::Logger.new('log/inibon.log')

  def self.model_name
    @my_model_name ||= ::ActiveModel::Name.new(self, Inibon)
  end

  statux %w{wip production deprecated}, required: true, column: :state, initial: 'wip'

  has_many :versionings, class_name: 'Inibon::Versioning', foreign_key: :version_id
  has_many :translations, through: :versionings, class_name: 'Inibon::Translation', source: :version # , foreign_key: :translation_id, source: :versions

  def identification
    "#{self.class.model_name}: #{self.id}"
  end

  def self.param_find(x)
    self.find_by_id(x.to_s)
  end

end

app/models/inibon/versioning.rb
class Inibon::Versioning < ActiveRecord::Base

  self.table_name= 'inibon_versionings'
  @@logger = ActiveSupport::Logger.new('log/inibon.log')

  belongs_to :translation, class_name: 'Inibon::Translation', foreign_key: :translation_id
  belongs_to :version, class_name: 'Inibon::Version', foreign_key: :version_id
  belongs_to :locale, class_name: 'Inibon::Locale', foreign_key: :locale_id, optional: true

  before_save :set_locale_from_translation

  def set_locale_from_translation
    self.locale = self.translation.locale
  end

end

app/controllers/inibon/application_controller.rb
module Inibon

  class ApplicationController < ::ApplicationController

    layout 'inibon/application'
    before_action :set_inibon_version

    def set_inibon_version
      Inibon::ArI18n.display_version = Inibon::Version.find_by_id(session[:display_version])
      Inibon::ArI18n.modify_version = Inibon::Version.find_by_id(session[:modify_version])
    end

  end

end

app/controllers/inibon/base_controller.rb
class Inibon::BaseController < Inibon::ApplicationController

  before_action :fetch_scope, except: [:landing]

  def landing
    render 'inibon/landing'
  end

  def show
    unless @thing = @scope.param_find(params[:id])
      redirect_to({action: :index},{error: 'Not Found'})
      return
    end
    render 'inibon/show'
  end

  def index
    @things = @scope.paginate(page: params[:page], per_page: 50)
    render 'inibon/index'
  end

  def new
    #@thing = @scope.new
    #ActiveRecord::QueryMethods::WhereChain
    @thing = @scope.new #@clazz.new(@scope.proxy_options[:conditions] & @clazz.column_names)
    @chain << @thing
    render 'inibon/new'
  end

  def create
    #@thing = @scope.new(params[:thingy])
    extra_params = @chain.inject({}) {|acc,x| acc.update(x.class.model_name.singular + '_id' => x.id) }
    @thing = @scope.new(extra_params.merge(params[:thingy])) #@clazz.new((@scope.proxy_options[:conditions].merge(extra_params) & @clazz.column_names).merge(params[:thingy]))
    if @thing.save
      @things = @scope.paginate(page: params[:page])
      render 'inibon/index'
    else
      render 'inibon/new'
    end
  end

  def update
    @thing = @clazz.find(@scope.param_find(params[:id]).try(:id))
    if @thing.update_attributes(params.require(:thingy).permit!)
      redirect_to [:inibon]+@chain, info: 'OK !'
    else
      render 'inibon/edit'
    end
  end

  def edit
    @thing = @scope.last
    render 'inibon/edit'
  end

  def destroy
    @thing = @scope.last
    @thing.destroy
    redirect_to [:inibon] + @chain[0..-2] + [@clazz.model_name.plural]
  end

  private

  def fetch_scope

    @chain = (request.path.split('/') - ['', 'inibon',params[:action], params[:action]+'!']).
      in_groups_of(2).
      map {|k,v| k.to_s.prepend('inibon/').singularize.camelize.constantize.param_find(v)}.
      compact.
      each {|x| instance_variable_set("@#{x.class.model_name.param_key}",x)}
    @clazz = (request.path - /\/inibon/).
      split('/').
      reverse.
      map(&:singularize).
      find {|x| %w[locale key translation].include?(x)}.
      prepend('inibon/').camelize.constantize
    @scope = {locale_id: :in_locale, key_id: :with_key}.
      inject(@clazz) { |klazz, (k,v)| params[k] ? klazz.send(v,params[k]) : klazz }
  end

end

app/controllers/inibon/i18n_hits_controller.rb
class Inibon::I18nHitsController < Inibon::BaseController
end

app/controllers/inibon/keys_controller.rb
class Inibon::KeysController < Inibon::BaseController

  before_action :set_key, only: [:show, :edit, :update, :destroy]

  include I18n::Backend::Flatten

  class Unflatten

    attr_accessor :h, :locale

    def initialize(keys, locale)
      @locale=locale
      default = Proc.new {|hash,key| hash[key] = Hash.new(&default) }
      @h=Hash.new(&default)

      keys.each do |k|
        k.split('.').reduce(@h){|acc,slug| acc[slug] }
      end
    end

    def populate
      process = Proc.new do |parent, key|
        last = key.split('.').last
        if parent[last].empty?
          parent[last] = Inibon::Translation.in_locale(@locale).with_key(key).last.try(:value)
        else
          parent[last].each do |k, v|
            process.call(parent[last], "#{key}.#{k}")
          end
        end
      end

      @h.each do |k,v|
        process.call(@h, k)
      end

      {@locale => @h}
    end

  end


  def to_yaml
    @locale = Inibon::Locale.find_by(key: params[:locale] || 'en')
    @u= Unflatten.new(Inibon::Key.all.pluck(:key),params[:locale])
    respond_to do |format|
      format.yaml { render plain: @u.populate.to_yaml }
      format.json { render json: @u.populate }
    end
  end

  def from_yaml
    if request.get?
      @locale = Inibon::Locale.find_by(key: params[:locale] || 'en')
      return
    end

    uploaded_io = params[:yaml].respond_to?(:to_io) ? params[:yaml].to_io : StringIO.new(params[:yaml])
    all = YAML.load(uploaded_io)

    @success,@failure={},{}

    version = Inibon::Version.last

    all.each do |locale_key,hash|
      @locale ||= Inibon::Locale.find_by(key: locale_key) || Inibon::Locale.create(key: locale_key, name: hash['general_lang_name'])

      f = flatten_translations(locale_key,hash,false,false)

      f.each do |k,v|
        Inibon::Key.ensure_key(k) do |b|
          t = Inibon::Translation.in_locale(@locale).with_key(b).build(value: v)
          (t.save ? @success : @failure).update(b.key => t)
          #t.versions << version
        end
      end
    end
  end

  def find
  end

  def create
    Inibon::Key.ensure_key(params[:thingy][:key])
    redirect_to action: :index
  end

  def show

    if @chain.find_all {|x| Inibon::Key === x}.length > 1
      @thing = @clazz.param_find(params[:id])
      @scope = @clazz.where()
      @chain.shift
    else
      unless @thing = @scope.param_find(params[:id])
        redirect_to({action: :index},{error: 'Not Found'})
        return
      end
    end
    render 'inibon/show'
  end

  def index
    if @chain.last.class == Inibon::Key
      @things = @scope.last.children.paginate(page: params[:page])
    else
      @things = @scope.paginate(page: params[:page])
    end
    render 'inibon/index'
  end

end

app/controllers/inibon/locales_controller.rb
class Inibon::LocalesController < Inibon::BaseController

  include I18n::Backend::Flatten

  def missing
    @keys = Inibon::Key.with_missing_locales(@locale.key)

    if request.post?
      l=Inibon::Locale.find_by_key(params[:copy_locale])
      @success,@failure={},{}

      @keys.inject({}){|acc,b| acc.update(b => Inibon::Translation.in_locale(l).with_key(b).last)}.each do |k,t|
        next unless t
        t = Inibon::Translation.in_locale(@locale).with_key(k).build(value: t.value)
        (t.save ? @success : @failure).update(k.key => t)
      end
      @keys = Inibon::Key.with_missing_locales(@locale.key)
    end

  end

  def from_yaml
    uploaded_io = params[:yaml].ergo {|x| x.respond_to?(:to_io) ? x.to_io : StringIO.new(x) }
    all = YAML.load(uploaded_io)

    @success,@failure={},{}

    version = Inibon::ArI18n.modify_version

    all.each do |locale_key,hash|
      @locale ||= Inibon::Locale.create(key: locale_key, name: hash['general_lang_name'])

      f = flatten_translations(locale_key,hash,false,false)

      f.each do |k,v|
        Inibon::Key.ensure_key(k) do |b|
          t = Inibon::Translation.in_locale(@locale).with_key(b).build(value: v)
          (t.save ? @success : @failure).update(b.key => t)
          t.versions << version
        end
      end
    end
  end

end

app/controllers/inibon/translations_controller.rb
class Inibon::TranslationsController < Inibon::BaseController

   def create
    #@thing = @scope.new(params[:thingy])
    extra_params = @chain.inject({}) {|acc,x| acc.update(x.class.model_name.param_key + '_id' => x.id) }
    #@thing = @clazz.new((@scope.proxy_options[:conditions].merge(extra_params) & @clazz.column_names).merge(params[:thingy]))
    @thing = @scope.new(extra_params.merge(params[:thingy])) #@clazz.new((@scope.proxy_options[:conditions].merge(extra_params) & @clazz.column_names).merge(params[:thingy]))

    @version = Inibon::Version.find(Inibon::ArI18n.modify_version)

    if previous = Inibon::Translation.in_locale(@locale).with_key(@key).in_version(@version).last
      previous.versions.delete(@version) 
    end
      
    @thing.versions << @version

    if @thing.save
      @things = @scope.paginate(page: params[:page])
      render 'inibon/index'
    else
      render 'inibon/new'
    end

   end

end

app/controllers/inibon/versions_controller.rb
# encoding: utf-8
class Inibon::VersionsController < Inibon::ApplicationController

  def show
    @version = Inibon::Version.find(params[:id])
  end

  def new
    @version = Inibon::Version.new
  end

  def edit
    @version = Inibon::Version.find(params[:id])
  end

  def update
    @version = Inibon::Version.find(params[:id])

    if @version.update_attributes(params[:version])
      flash.now[:error]='Unable to save version'
      render 'edit'
    else
      redirect_to({action: :index},messages: 'successfully updated')
    end
  end

  def change
    session[:display_version]= params[:display_version].try(:to_i)
    session[:modify_version] = params[:modify_version].try(:to_i)
    redirect_to action: :index
  end

  def index
    @versions = Inibon::Version.all
  end

  def create
    last_version= Inibon::Version.order('id DESC').first
    @version = Inibon::Version.new(params.require(:version).permit!)

    if @version.save
      @version.translations = last_version.try(:translations) || Inibon::Translation.all
      redirect_to [:inibon,@version]
    else
      render 'new'
    end
  end

end

app/helpers/inibon/application_helper.rb
module Inibon
  module ApplicationHelper
  end
end

app/views/inibon/_breadcrumb.html.haml
- breadcrumbs = nil unless local_assigns.has_key?(:breadcrumbs)

= link_to 'Inibon', inibon.url_for([:root])
= ">"

- if breadcrumbs
  - breadcrumbs.each do |label,path|
    = link_to label, path 
    = ">"
- else
  - @chain.dup.each_with_index do |x,i|
    = link_to x.class.model_name.plural, inibon.url_for(@chain.first(i) + [x.class.model_name.route_key.to_sym])
    = ">"
    = link_to x.identification, inibon.url_for(@chain.first(i) + [x])
    = ">"
  
  - if @thing
    = @thing.identification
  - elsif @things
    = @clazz.model_name.plural

app/views/inibon/_versions.html.haml
= form_tag inibon.url_for([:change,:versions]) do
  = label_tag :display_version, 'Display Version'
  = select_tag :display_version, options_for_select([['elige',0]]+Inibon::Version.all.map{|x| [x.name || x.id, x.id] }, selected: Inibon::ArI18n.display_version.try(:id))

  = label_tag :modify_version, 'Modifying Version'
  = select_tag :modify_version, options_for_select([['elige',0]]+Inibon::Version.all.map{|x| [x.name || x.id, x.id] }, selected: Inibon::ArI18n.modify_version.try(:id))

  = submit_tag 'Cambiar', class: 'btn btn-xs'

app/views/inibon/edit.html.haml
%h1 Editing #{@clazz.model_name.singular} #{@chain.last.id}

= form_for(@chain.last, as: :thingy,  url: inibon.url_for(@chain), html: {class: 'form', method: :put}) do |f|
  = render 'inibon/shared/errors', object: f.object, name: f.object.class.name
  = render 'form', f: f
  = f.submit 'Update', class: 'btn'

= link_to 'Show', inibon.polymorphic_url(@chain), class: 'btn'
= link_to 'Back', inibon.polymorphic_url(@chain[0..-2] + [@clazz.model_name.route_key]), class: 'btn'

app/views/inibon/index.html.haml
.breadcrumb
  = render 'inibon/breadcrumb'
  = render 'inibon/versions'

%h1 Listing #{@clazz.model_name.plural} for #{@chain.map{|x| x.identification}.join(' > ')}

- begin
  = render "inibon/#{@clazz.model_name.plural}/#{params[:action]}"
- rescue ActionView::MissingTemplate

.row
  .col-xs-6
    = link_to "New #{@clazz.name}", inibon.url_for([:new] + @chain + [@clazz.model_name.param_key.to_sym]), class: 'btn btn-primary btn-lg'
  - if false # TODO
    .col-xs-6
      = form_tag url: find_key_path, html: {method: :get, class: 'form-inline'} do
        .form-group
          = text_field_tag :key, placeholder: 'Key', class: 'form-control'
        .form-group
          = submit_tag 'Buscar palabra clave'
%br

%table.table.table-bordered.table-striped
  %thead
    %tr
      - @clazz.column_names.each do |k|
        %th
          = k.to_s.humanize
      %th.actions

  %tbody
    - @things.each do |thing|
      %tr
        - @clazz.column_names.each do |k|
          %td= k == 'id' ? link_to(content_tag(:strong, thing.send(k)),inibon.url_for(@chain + [thing]), class: 'btn btn-primary') : h(thing.send(k))
        %td
          = link_to 'Show', inibon.url_for(@chain + [thing]), class: 'btn btn-info btn-sm'
          = link_to 'Edit', inibon.url_for([:edit] + @chain + [thing]), class: 'btn btn-warning btn-sm'
          = link_to 'Destroy', inibon.url_for( @chain + [thing]), confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger btn-sm'

.row
  .col-xs-12
    = will_paginate(@things, {renderer: BootstrapPagination::Rails})

= link_to "New #{@clazz.name}", inibon.url_for([:new] + @chain + [@clazz.model_name.param_key.to_sym]), class: 'btn btn-primary btn-lg'

app/views/inibon/landing.html.haml
%h1 Copies

%h2= link_to 'Versiones', inibon.url_for([:versions])
%ul
  - Inibon::Version.order('id DESC').limit(4).all.each do |l|
    %li= link_to "#{l.name} (#{l.id}): ", inibon.url_for([l])

%h2= link_to 'Locales', inibon.url_for([:locales])
%ul
  - Inibon::Locale.all.map{|x| [x,Inibon::Key.with_missing_locales(x.key).count('id')] }.each do |l,cnt|
    %li!= "#{l.name} (#{l.key}): " + (cnt.zero? ? "No missing translations" : link_to("#{cnt} missing translations", inibon.url_for([:missing,l])))
%h2= link_to 'Keys', inibon.keys_path
%h2= link_to 'Translations', inibon.translations_path

%h2 Idiomas:

%ul
  - Inibon::Locale.all.each do |l|
    %li= link_to l.name, inibon.url_for([l])

app/views/inibon/new.html.haml
.breadcrumb
  = render 'inibon/breadcrumb'
  = render 'inibon/versions'

%h1 Nuevo #{@clazz.model_name.param_key.humanize} para #{@chain.map{|x| x.identification}.join(' > ')}

= form_for(@chain.last, as: :thingy, url: inibon.url_for(@chain), html: {class: 'form'}) do |f|
  = render 'inibon/shared/errors', object: f.object, name: f.object.class.name
  = render "form", f: f
  = f.submit 'Create', class: 'btn'

= link_to 'Show', inibon.polymorphic_url(@chain)
= link_to 'Back', inibon.polymorphic_url(@chain[0..-2] + [@clazz.model_name.route_key.to_sym])

app/views/inibon/show.html.haml
.breadcrumb
  = render 'inibon/breadcrumb'
  = render 'inibon/versions'

%h1 Showing #{@thing.identification}

- begin
  = render "inibon/#{@clazz.model_name.route_key}/#{params[:action]}"
- rescue ActionView::MissingTemplate
  = "Error rendering #{"inibon/#{@clazz.model_name.route_key}/#{params[:action]}"}"

%table.table.bordered
  %thead
    %tr
      %th Attribute
      %th Value
  %tbody
    - @clazz.reflect_on_all_associations.each do |assoc|
      - case assoc.macro
      - when :has_many
        - begin
          %tr
            %td= "#{assoc.macro} #{assoc.name}"
            %td= link_to "#{assoc.class_name.constantize.model_name.route_key} (#{@thing.send(assoc.name).count})",
              inibon.url_for(((@chain) + [assoc.class_name.constantize.model_name.route_key.to_sym]).uniq), class: 'btn'
        - rescue => e
          %tr
            %td= "#{assoc.macro} #{assoc.name}"
            %td= "(Exception: #{e.message})"
      - when :belongs_to
        - if @thing.send(assoc.name)
          %tr
            %td= "#{assoc.macro} #{assoc.name}"
            %td= link_to @thing.send(assoc.name).try(:identification), inibon.url_for([@thing.send(assoc.name)]), class: 'btn'

    - @clazz.column_names.each do |k|
      %tr
        %td= k.to_s.humanize
        %td= @thing.send(k.to_s).pretty_inspect
  
= link_to 'Edit', inibon.url_for([:edit]+@chain), class: 'btn'
= link_to 'Back', inibon.polymorphic_url(@chain[0..-2] + [@clazz.model_name.route_key.to_sym.to_sym]), class: 'btn'